### ISSUE TITLE
DUEL_DISTRICT Objects disappearing and reappering based on range

### ISSUE THREAD

**Issue by Crisis0** [punyhumangames/BladeSymphony#15]
Title

VIDEO: [CLICK ME](https://www.youtube.com/watch?v=WXXCQeaAKJU)

**Comment by urinal-cake** [comment]
This should be fixed in the latest build available on Steam. Can you please test?

**Comment by Retromagnetic** [comment]
Still happens on 'the street' with the lights/ads in the background. But it's not based on distance, it feels pretty random. 

![20180712140145_1](https://user-images.githubusercontent.com/36271885/42632048-4421a670-85dc-11e8-8488-37b72982ab10.jpg)
![20180712140127_1](https://user-images.githubusercontent.com/36271885/42632059-4e361de4-85dc-11e8-8806-dc072a6c2b5e.jpg)

**Comment by misyltoad** [comment]
This got fixed, it was related to vertex type stuff.
